name: fluttershow_base
description: Foundation library for the Fluttershow framework
version: 1.0.0
homepage: https://github.com/lucas-goldner/FlutterShow

environment:
  sdk: ">=3.0.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  arrow_path: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
